# -*- coding: utf-8 -*-
"""precos_imoveis_corrigido.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14wSu1JdBIMfCa9e8--_uPFhoVEjq9SfV
"""

st.title("**Atividade Avaliativa - Preços de Imóveis**")
st.subheader("**Alunos:**")
st.write("- Gabriele Martinez")
st.write("- Julia Capellini")
st.write("- Lucas Gimenez")

st.write("**Objetivo:** Prever o preço de venda de imóveis residenciais baseado em suas características.")

st.write("**Contexto do Problema:** A precificação de imóveis é crucial no mercado imobiliário. O preço depende de múltiplos fatores como tamanho, qualidade, localização e amenities.")

st.write("## Etapa 1 - Análise Exploratória")

st.write("Primeiro, começamos importando as possíveis bibliotecas que usaremos para iniciar a exploração dos dados.")


import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LinearRegression, Ridge
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import cross_val_score, KFold
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score, mean_absolute_percentage_error

st.markdown("""Nessa etapa, precisamos entender como os dados do nosso dataset se comportam e como as variáveis se relacionam com o preço do imóvel.

Primeiro, importaremos o dataset de treino para treinarmos o algoritmo.
""")

# Importando o Dataset de treino
df_imoveis = pd.read_csv('train.csv')

# Mostrando as primeiras linhas para confirmar a importação
df_imoveis.head()

st.markdown("""Aqui, vamos plotar o histograma do preço e verificar as assimetrias.

Podemos verificar que o gráfico está assimétrico, o que significa que a maioria das casas tem preços mais baixos, mas algumas poucas casas bem caras acabam por esticar o gráfico para a direita.
""")

plt.figure(figsize=(10, 6))
sns.histplot(df_imoveis['SalePrice'], kde=True)
plt.title('Distribuição do Preço de Venda')
plt.xlabel('Preço de Venda')
plt.ylabel('Frequência')
st.pyplot(plt.gcf())
plt.clf()

# Calculando a Assimetria (Skewness)
assimetria = df_imoveis['SalePrice'].skew()
st.write(f"Skewness (Assimetria) de SalePrice: {assimetria:.2f}")

st.markdown("""Agora, plotaremos um gráfico de dispersão (scatter plot) cruzando a área construída do imóvel com o preço.

Esse gráfico é fundamental para identificar os outliers que teremos que remover na próxima etapa.
""")

plt.figure(figsize=(10, 6))
sns.scatterplot(x=df_imoveis['GrLivArea'], y=df_imoveis['SalePrice'])
plt.title('Área Construída vs Preço (GrLivArea vs SalePrice)')
plt.xlabel('Área Construída Acima do Solo (sq ft)')
plt.ylabel('Preço de Venda')
st.pyplot(plt.gcf())
plt.clf()

st.markdown("""Com o gráfico, podemos observar que sim, há Outliers, pois temos algumas casas que possuem área maior que 4000 mas com prreços muito baixos.

A seguir, montaremos um boxplot cruzando a qualidade geral do imóvel com o seu preço.
""")

plt.figure(figsize=(10, 6))
sns.boxplot(x=df_imoveis['OverallQual'], y=df_imoveis['SalePrice'])
plt.title("Qualidade do Imóvel vs Preço (OverallQual vs SalePrice)")
plt.xlabel("Qualidade Geral (1 a 10)")
plt.ylabel("Preço de Venda")
st.pyplot(plt.gcf())
plt.clf()

st.markdown("""Por fim, precisamos ver quais variáveis numéricas têm a correlação mais forte com o preço.

Como nosso dataset tem muitas colunas, vamos pegar apenas as variáveis numéricas e focar nas que mais se relacionam com o preço de venda.
""")

# Selecionando apenas as colunas numéricas
df_numericas = df_imoveis.select_dtypes(include=['int64','float64'])

# Calculando a correlação com o SalePrice e pegar as 10 maiores
correlacoes = df_numericas.corr()
top_features = correlacoes.nlargest(10, 'SalePrice')['SalePrice'].index

# Plotando o HeatMap das 10 variáveis mais correlacionadas
plt.figure(figsize=(10, 8))
sns.heatmap(df_numericas[top_features].corr(), annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Heatmap de Correlação - Top 10 Features')
st.pyplot(plt.gcf())
plt.clf()

st.markdown("""### Etapa 2 - Pré Processamento

Nessa etapa, nós limparemos os dados para prepará-los para o modelo, porém tomando cuidado para não cometer o erro de Data Leakage.

Para que isso não ocorra, precisamos aplicar as transformações corretamente.
""")

# Primeiro, vamos remover alguns Outliers específicos, que são Área > 4000 e Preço < 300.000
df_removendo_outliers = df_imoveis.drop(df_imoveis[(df_imoveis['GrLivArea'] > 4000) & (df_imoveis['SalePrice'] < 300000)].index)

# Criando a coluna TotalSF
df_removendo_outliers['TotalSF'] = df_removendo_outliers['TotalBsmtSF'] + df_removendo_outliers['1stFlrSF'] + df_removendo_outliers['2ndFlrSF']

st.markdown("""Como vimos no Histograma, o preço possui uma assimetria positiva. Para isso, vamos aplica uma transformação logaritmixa para aproximar os dados de uma distribuição normal.""")

# Aplicando a transformação log1p no target
y = np.log1p(df_removendo_outliers['SalePrice'])

# Separando as variáveis de entrada (features)
X = df_removendo_outliers.drop('SalePrice', axis=1)

st.markdown("""A revisão precisa ser feita antes do cálculo das médas para preencher os nulos ou escalonar os dados, se não as informações do teste "vazam" para o treino.

Para isso, faremos a distribuição 60/20/20.
""")

# Passo 1: Separando 60% para treino e 40% temporário
X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.4, random_state=42)

# Passo 2: Dividir os 40% restantes na metaded (20% Validação e 20% Teste)
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42)

st.write(f"Treino: {len(X_train)} | Validação: {len(X_val)} | Teste: {len(X_test)}")

st.markdown("""Para tratar os valores ausentes, vamos aplicar o escalonamento numérico e os Encodings. Para isso, vamos usar a estrutura de Pipeline e ColumnTransformer.""")

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder, OrdinalEncoder

# Definindo quais colunas são numéricas, ordinais e nominais
colunas_num = ['TotalSF', 'GrLivArea', 'GarageCars', 'OverallQual']
colunas_ord = ['ExterQual']
colunas_nom = ['Neighborhood', 'SaleCondition']

# Pipeline Numérico, aqui preenchemos os nulos com a mediana e padronizamos (Z-Score)
pipe_num = Pipeline([
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

# Pipelina Ordinal: Preenche nulos com moda e aplica OrdinalEncoder
pipe_ord = Pipeline([
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('encoder', OrdinalEncoder())
])

# Pipeline Nominal: Preenche nulos com moda e aplica OneHotEncoder
pipe_nom = Pipeline([
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('encoder', OneHotEncoder(handle_unknown='ignore', sparse_output=False))
])

# Incluindo tudo no ColumnTransformer
preprocessor = ColumnTransformer([
    ('num', pipe_num, colunas_num),
    ('ord', pipe_ord, colunas_ord),
    ('nom', pipe_nom, colunas_nom)
])

# Usamos o fit_transform só no treino, na validação e no teste usamos apenas transform
X_train_prep = preprocessor.fit_transform(X_train)
X_val_prep = preprocessor.transform(X_val)
X_test_prep = preprocessor.transform(X_test)

st.write("Pré-processamento concluído com sucesso e sem Data Leakage!")

"""### Etapa 3 - Comparação de Modelos

Nessa etapa, precisamos implementar três modelos, utilizar a validação cruzada K-Fold com K=5, gerar uma tabela com as métricas MAE, MSE, RMSE, R² e MAPE e plotar três gráficos, contendo Valores Reais vs. Preditos, Gráfico de Resíduos e Feature Importance.
"""

# Inicializando os 3 modelos exigidos
modelos = {
    'Linear Regression': LinearRegression(),
    'Ridge': Ridge(alpha=1.0),
    'Random Forest': RandomForestRegressor(random_state=42)
}

# Configurando o K-Fold com K-5
kf = KFold(n_splits=5, shuffle=True, random_state=42)

st.write("=== VALIDAÇÃO CRUZADA (R² Médio no Treino) ===")
for nome, modelo in modelos.items():
  # Avaliando os modelos usando o R²
  cv_scores = cross_val_score(modelo, X_train_prep, y_train, cv=kf, scoring='r2')
  st.write(f"{nome}: {cv_scores.mean():.4f}")

st.markdown("""Agora iremos treinar os modelos de fato, prever os valores da base de validação e calcular as métricas exigidas.""")

# Criando dicionários para guardar as previsões para os gráficos depois
resultados_reais = {}
resultados_preditos = {}

st.write("=== Métricas na Base de Validação")
for nome, modelo in modelos.items():
  # Treina o modelo com os dados de treino preparados
  modelo.fit(X_train_prep, y_train)

  # Faz a previsão na base de validação
  y_pred_log = modelo.predict(X_val_prep)

  # Revertendo o Logaritmo para ter o preço real em dinheiro
  y_val_real = np.expm1(y_val)
  y_pred_real = np.expm1(y_pred_log)

  # Guardando para os gráficos
  resultados_reais[nome] = y_val_real
  resultados_preditos[nome] = y_pred_real

  # Calculando as métricas exigidas
  mae = mean_absolute_error(y_val_real, y_pred_real)
  mse = mean_squared_error(y_val_real, y_pred_real)
  rmse = np.sqrt(mse)
  r2 = r2_score(y_val_real, y_pred_real)
  mape = mean_absolute_percentage_error(y_val_real, y_pred_real)

  # Exibindo a tabela
  st.write(f"\nModelo: {nome}")
  st.write(f"MAE:  {mae:,.2f}")
  st.write(f"MSE:  {mse:,.2f}")
  st.write(f"RMSE: {rmse:,.2f}")
  st.write(f"R²:   {r2:.4f}")
  st.write(f"MAPE: {mape:.4f} ({mape*100:.2f}%)")

# Usando o Linear Regression para os gráficos
y_real_rf = resultados_reais['Linear Regression']
y_pred_rf = resultados_preditos['Linear Regression']
residuos = y_real_rf - y_pred_rf

# Gráfico de Valores Reais vs. Preditos
plt.figure(figsize=(8, 5))
plt.scatter(y_real_rf, y_pred_rf, alpha=0.5, color='blue')
# Linha de acerto perfeito (diagonal)
plt.plot([y_real_rf.min(), y_real_rf.max()], [y_real_rf.min(), y_real_rf.max()], 'r--', lw=2)
plt.title('Valores Reais vs Preditos (Linear Regression)')
plt.xlabel('Preço Real do Imóvel')
plt.ylabel('Preço Predito pelo Modelo')
st.pyplot(plt.gcf())
plt.clf()

# Gráfico de Resíduos (Erros)
plt.figure(figsize=(8, 5))
plt.scatter(y_pred_rf, residuos, alpha=0.5, color='purple')
plt.axhline(0, color='r', linestyle='--', lw=2) # Linha do erro zero
plt.title('Gráfico de Resíduos (Linear Regression)')
plt.xlabel('Preço Predito')
plt.ylabel('Resíduos (Real - Predito)')
st.pyplot(plt.gcf())
plt.clf()

# Gráfico de Feature Importance (Importância das Variáveis - COEFICIENTES)
coeficientes = modelos['Linear Regression'].coef_
# Pegando os nomes das colunas geradas pelo ColumnTransformer
nomes_features = preprocessor.get_feature_names_out()

# Criando uma série Pandas com os coeficientes
feat_imp = pd.Series(coeficientes, index=nomes_features)

# Ordenando pelo valor absoluto para pegar as 10 variáveis de MAIOR IMPACTO (positivo ou negativo)
feat_imp_ordenada = feat_imp.reindex(feat_imp.abs().sort_values(ascending=False).index).head(10)

plt.figure(figsize=(10, 6))
# Mudamos a paleta para 'coolwarm' para ver mais fácil o que é positivo e negativo
sns.barplot(x=feat_imp_ordenada.values, y=feat_imp_ordenada.index, hue=feat_imp_ordenada.index, legend=False, palette='coolwarm')
plt.title('Top 10 Feature Importance (Coeficientes) - Linear Regression')
plt.xlabel('Valor do Coeficiente (Impacto no Preço)')
plt.ylabel('Features (Variáveis)')
st.pyplot(plt.gcf())
plt.clf()

st.markdown("""### Etapa 4 - Análise Comparativa e Avaliação Final

Com os modelos treinados e avaliados na base de validação, agora vamos aprofundar a análise: identificar o melhor modelo, realizar o tuning de hiperparâmetros e, por fim, avaliá-lo no conjunto de teste.

#### Tuning de Hiperparâmetros (GridSearchCV)

Antes de avaliar no teste, vamos refinar o Random Forest, que apresentou os melhores resultados na validação. Usaremos o GridSearchCV para encontrar a combinação ideal de hiperparâmetros.
""")

from sklearn.model_selection import GridSearchCV

# Definindo o grid de hiperparâmetros para o Random Forest
param_grid = {
    'n_estimators': [100, 200],
    'max_depth': [None, 10, 20],
    'min_samples_split': [2, 5]
}

# Aplicando o GridSearchCV com KFold (k=5) no conjunto de treino
rf_grid = GridSearchCV(
    RandomForestRegressor(random_state=42),
    param_grid,
    cv=kf,
    scoring='r2',
    n_jobs=-1
)

rf_grid.fit(X_train_prep, y_train)

st.write("Melhores hiperparâmetros encontrados:")
st.write(rf_grid.best_params_)
st.write(f"\nMelhor R² na validação cruzada (treino): {rf_grid.best_score_:.4f}")

st.markdown("""Com os melhores hiperparâmetros em mãos, vamos agora avaliar o modelo otimizado na base de validação para confirmar a melhoria.""")

# Avaliando o modelo otimizado na base de validação
y_pred_rf_otimizado_log = rf_grid.best_estimator_.predict(X_val_prep)
y_pred_rf_otimizado_real = np.expm1(y_pred_rf_otimizado_log)
y_val_real = np.expm1(y_val)

mae_ot = mean_absolute_error(y_val_real, y_pred_rf_otimizado_real)
rmse_ot = np.sqrt(mean_squared_error(y_val_real, y_pred_rf_otimizado_real))
r2_ot = r2_score(y_val_real, y_pred_rf_otimizado_real)

st.write("=== Random Forest Otimizado (Validação) ===")
st.write(f"MAE:  {mae_ot:,.2f}")
st.write(f"RMSE: {rmse_ot:,.2f}")
st.write(f"R²:   {r2_ot:.4f}")

st.markdown("""#### Avaliação Final no Conjunto de Teste

Agora chegou a hora de usar o conjunto de teste, que ficou completamente isolado durante todo o processo.
""")

# Avaliando o melhor modelo (Random Forest otimizado) na base de TESTE
y_pred_teste_log = rf_grid.best_estimator_.predict(X_test_prep)

# Revertendo o logaritmo para obter os preços reais
y_test_real = np.expm1(y_test)
y_pred_teste_real = np.expm1(y_pred_teste_log)

mae_test = mean_absolute_error(y_test_real, y_pred_teste_real)
mse_test = mean_squared_error(y_test_real, y_pred_teste_real)
rmse_test = np.sqrt(mse_test)
r2_test = r2_score(y_test_real, y_pred_teste_real)
mape_test = mean_absolute_percentage_error(y_test_real, y_pred_teste_real)

st.write("=== Avaliação Final: Random Forest Otimizado (Teste) ===")
st.write(f"MAE:  {mae_test:,.2f}")
st.write(f"MSE:  {mse_test:,.2f}")
st.write(f"RMSE: {rmse_test:,.2f}")
st.write(f"R²:   {r2_test:.4f}")
st.write(f"MAPE: {mape_test:.4f} ({mape_test*100:.2f}%)")

st.markdown("""Plotamos abaixo os gráficos de Valores Reais vs. Preditos e de Resíduos para o conjunto de teste, para verificar se o comportamento do modelo se mantém consistente com o que observamos na validação.""")

residuos_teste = y_test_real - y_pred_teste_real

# Gráfico Reais vs Preditos no Teste
plt.figure(figsize=(8, 5))
plt.scatter(y_test_real, y_pred_teste_real, alpha=0.5, color='green')
plt.plot([y_test_real.min(), y_test_real.max()], [y_test_real.min(), y_test_real.max()], 'r--', lw=2)
plt.title('Valores Reais vs Preditos - Teste (Random Forest Otimizado)')
plt.xlabel('Preço Real do Imóvel')
plt.ylabel('Preço Predito pelo Modelo')
st.pyplot(plt.gcf())
plt.clf()

# Gráfico de Resíduos no Teste
plt.figure(figsize=(8, 5))
plt.scatter(y_pred_teste_real, residuos_teste, alpha=0.5, color='darkorange')
plt.axhline(0, color='r', linestyle='--', lw=2)
plt.title('Gráfico de Resíduos - Teste (Random Forest Otimizado)')
plt.xlabel('Preço Predito')
plt.ylabel('Resíduos (Real - Predito)')
st.pyplot(plt.gcf())
plt.clf()

st.markdown("""#### Análise dos Padrões dos Resíduos

Observando o gráfico de resíduos, podemos identificar em que faixas de preço o modelo erra mais e se há padrões sistemáticos nos erros.
""")

# Analisando os resíduos por faixa de preço
faixas = pd.cut(y_test_real, bins=[0, 100000, 200000, 300000, 500000, float('inf')],
                labels=['< 100k', '100k-200k', '200k-300k', '300k-500k', '> 500k'])

df_residuos = pd.DataFrame({
    'Preço Real': y_test_real.values,
    'Resíduo': residuos_teste.values,
    'Faixa de Preço': faixas.values
})

# Erro absoluto médio por faixa
erro_por_faixa = df_residuos.groupby('Faixa de Preço', observed=True)['Resíduo'].apply(lambda x: x.abs().mean())

st.write("=== Erro Absoluto Médio por Faixa de Preço ===")
st.write(erro_por_faixa.to_string())

# Plotando o boxplot dos resíduos por faixa
plt.figure(figsize=(10, 5))
sns.boxplot(x='Faixa de Preço', y='Resíduo', data=df_residuos, palette='Set2')
plt.axhline(0, color='r', linestyle='--', lw=2)
plt.title('Distribuição dos Resíduos por Faixa de Preço (Teste)')
plt.xlabel('Faixa de Preço')
plt.ylabel('Resíduo (Real - Predito)')
st.pyplot(plt.gcf())
plt.clf()